### PR TITLE
navbar profile fix

### PR DESCRIPTION
**Pull request by Jukaro**
Navbar profile component no longer add multiple event listeners for nothing when being called multiple time to redirect to user's profile (no more 10 thousands fetches)

### CODE REVIEW

**Comment by Rreyth** [comment]
LGFM

**Comment by Rreyth** [comment]
image
en faite non

**Comment by Rreyth** [comment]
block user search doesn't show up

**Review by swotex — APPROVED** [review]
LGFM

**Review by ltuffery — APPROVED** [review]
LGFM

**Pull request merged**
